### ISSUE TITLE
can you support schema:domain/rangeIncludes ?

### ISSUE THREAD

**Issue by VladimirAlexiev** [lambdamusic/Ontodocs#16]
https://rawgit.com/euBusinessGraph/eubg-data/master/ontology/prop-ebgadminunitl6.html shows no meaningful domain and range. We define it as follows:
```turtle
ebg:adminUnitL6 a owl:ObjectProperty ;
  schema:domainIncludes locn:Address ;
  schema:rangeIncludes ebg:LAURegion ;
  rdfs:label "Municipality/Commune/Settlement" ;
  rdfs:isDefinedBy ebg: ;
  skos:definition "LAU2 region of the address." .
```
We use schema:domain/rangeIncludes because they allow polymorphic properties, whereas rdfs:domain/range bind a property to a single class, so they restrict flexibility and don't promote reuse.

I selected Ontodocs because I saw your schema.org example http://www.michelepasin.org/support/ontospy-examples/schema_org_topbraidttl/prop-schemaaction.html so I assumed you support schema:domain/rangeIncludes. But I notice now this is "Schema.org (converted to OWL by TopQuadrant)", and it uses rdfs:domain/range:
```turtle
schema:action a owl:DatatypeProperty ;
    rdfs:label "action"^^xsd:string ;
    schema:supersededBy schema:muscleAction ;
    rdfs:comment "The movement the muscle generates." ;
    rdfs:domain schema:Muscle ;
    rdfs:range xsd:string .
```

Unfortunately no doc generator supports schema:domain/rangeIncludes, except schema's own generator :-(. Is there a chance ontodoc will support it?

**Comment by VladimirAlexiev** [comment]
https://github.com/OnToology/OnToology/issues/383

**Comment by VladimirAlexiev** [comment]
Another symptom: https://rawgit.com/euBusinessGraph/eubg-data/master/ontology/class-schemageocoordinates.html 
"Instances of schema:GeoCoordinates can have the following properties.... From class owl:Thing" and then all props in the ontology.
Since it assumes all domains/ranges are owk:Thing, it assumes all properties apply anywhere.

**Comment by VladimirAlexiev** [comment]
Please submit a PR to @lambdamusic

**Comment by sumutcan** [comment]
@VladimirAlexiev @lambdamusic 
PR [https://github.com/lambdamusic/Ontospy/pull/46](url)

**Comment by lambdamusic** [comment]
Thanks @sumutcan and @VladimirAlexiev - this is a great addition.
