### ISSUE TITLE
Complex domains are not interpreted correctly

### ISSUE THREAD

**Issue by jo-tud** [lambdamusic/Ontodocs#3]
When a domain is a union it is not interpreted correctly. Therefore, properties for owl:Thing are shown (see 
http://ethon.consensys.net/prop-blockdifficulty.html)

````
    rdfs:domain [ a owl:Class ;
            owl:unionOf ( :Block :Uncle ) ] ;
````

**Comment by lambdamusic** [comment]
Very good point, thanks for raising that (btw nice website!)

**Comment by lambdamusic** [comment]
The error has been fixed with v1.1.2. 

Just upgrade ontospy/ontodocs: 

```
pip install ontodocs -U
```

**Comment by jo-tud** [comment]
Thanks!
However, now I get `Blank node (see implementation)`. See http://ethon.consensys.net/prop-blockdifficulty.html
But it should show `:Block` and  `:Uncle` as domains.

Ontodocs is great!

**Comment by ThemisB** [comment]
Is there any update on this issue?
